### PR TITLE
Type stable and safe way to pass ioctx parameter to libxml

### LINKED ISSUE #200: Using `StreamReader` with TranscodingStreams leads to random Segmentation faults
Discovered in https://github.com/felipenoris/XLSX.jl/pull/273#issuecomment-2402631466

MWE:

```julia
using TranscodingStreams
using EzXML

undirected = """
<?xml version="1.0" encoding="UTF-8"?>
<graphml>
    <graph edgedefault="undirected">
        <node id="n0"/>
        <node id="n1"/>
        <edge source="n0" target="n1"/>
    </graph>
</graphml>
"""

reader = EzXML.StreamReader(NoopStream(IOBuffer(undirected)))

GC.gc()
GC.gc()
GC.gc()

while (item = iterate(reader)) != nothing
    @show reader.type, reader.name
end
```

```
Internal error: during type inference of
var"#17"(0x00007f7c7649b4f0, Ptr{UInt8}, Int32)
Encountered unexpected error in runtime:
MethodError(f=Core.Compiler.widenconst, args=(0x00007f7c7649b4f0,), world=0x0000000000001734)
jl_method_error_bare at /cache/build/builder-amdci5-1/julialang/julia-master/src/gf.c:2254
jl_method_error at /cache/build/builder-amdci5-1/julialang/julia-master/src/gf.c:2272
jl_lookup_generic_ at /cache/build/builder-amdci5-1/julialang/julia-master/src/gf.c:3106 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-1/julialang/julia-master/src/gf.c:3121
#408 at ./compiler/typeutils.jl:57
anymap at ./compiler/utilities.jl:43 [inlined]
argtypes_to_type at ./compiler/typeutils.jl:57
abstract_call_known at ./compiler/abstractinterpretation.jl:2199
abstract_call at ./compiler/abstractinterpretation.jl:2282
abstract_call at ./compiler/abstractinterpretation.jl:2275
abstract_call at ./compiler/abstractinterpretation.jl:2420
abstract_eval_call at ./compiler/abstractinterpretation.jl:2435
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2451
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2749
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:3065
typeinf_local at ./compiler/abstractinterpretation.jl:3319
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3401
_typeinf at ./compiler/typeinfer.jl:244
typeinf at ./compiler/typeinfer.jl:215
typeinf_ext at ./compiler/typeinfer.jl:1101
typeinf_ext_toplevel at ./compiler/typeinfer.jl:1139
typeinf_ext_toplevel at ./compiler/typeinfer.jl:1135
jfptr_typeinf_ext_toplevel_39604.1 at /home/nathan/.julia/juliaup/julia-1.11.0+0.x64.linux.gnu/lib/julia/sys.so (unknown line)
jl_apply at /cache/build/builder-amdci5-1/julialang/julia-master/src/julia.h:2157 [inlined]
jl_type_infer at /cache/build/builder-amdci5-1/julialang/julia-master/src/gf.c:390
jl_generate_fptr_impl at /cache/build/builder-amdci5-1/julialang/julia-master/src/jitlayers.cpp:511
jl_compile_method_internal at /cache/build/builder-amdci5-1/julialang/julia-master/src/gf.c:2536 [inlined]
jl_compile_method_internal at /cache/build/builder-amdci5-1/julialang/julia-master/src/gf.c:2423
_jl_invoke at /cache/build/builder-amdci5-1/julialang/julia-master/src/gf.c:2940 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-1/julialang/julia-master/src/gf.c:3125
unknown function (ip: 0x7f7c6fc95b5f)
xmlParserInputBufferGrow at /workspace/srcdir/libxml2-2.13.3/xmlIO.c:2362
xmlTextReaderPushData at /workspace/srcdir/libxml2-2.13.3/xmlreader.c:790
xmlTextReaderRead at /workspace/srcdir/libxml2-2.13.3/xmlreader.c:1219
macro expansion at /home/nathan/.julia/packages/EzXML/DL8na/src/error.jl:50 [inlined]
read_node at /home/nathan/.julia/packages/EzXML/DL8na/src/streamreader.jl:199 [inlined]
iterate at /home/nathan/.julia/packages/EzXML/DL8na/src/streamreader.jl:190 [inlined]
iterate at /home/nathan/.julia/packages/EzXML/DL8na/src/streamreader.jl:190
unknown function (ip: 0x7f7c6fca6b03)
top-level scope at /home/nathan/Documents/breakezxml/stuff.jl:21
jl_toplevel_eval_flex at /cache/build/builder-amdci5-1/julialang/julia-master/src/toplevel.c:934
jl_toplevel_eval_flex at /cache/build/builder-amdci5-1/julialang/julia-master/src/toplevel.c:886
ijl_toplevel_eval_in at /cache/build/builder-amdci5-1/julialang/julia-master/src/toplevel.c:994
eval at ./boot.jl:430 [inlined]
include_string at ./loading.jl:2628
_include at ./loading.jl:2688
include at ./Base.jl:557
jfptr_include_46600.1 at /home/nathan/.julia/juliaup/julia-1.11.0+0.x64.linux.gnu/lib/julia/sys.so (unknown line)
exec_options at ./client.jl:323
_start at ./client.jl:531
jfptr__start_72051.1 at /home/nathan/.julia/juliaup/julia-1.11.0+0.x64.linux.gnu/lib/julia/sys.so (unknown line)
jl_apply at /cache/build/builder-amdci5-1/julialang/julia-master/src/julia.h:2157 [inlined]
true_main at /cache/build/builder-amdci5-1/julialang/julia-master/src/jlapi.c:900
jl_repl_entrypoint at /cache/build/builder-amdci5-1/julialang/julia-master/src/jlapi.c:1059
main at /cache/build/builder-amdci5-1/julialang/julia-master/cli/loader_exe.c:58
unknown function (ip: 0x7f7c8706cd8f)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x4010b8)

[1905095] signal 11 (1): Segmentation fault
in expression starting at /home/nathan/Documents/breakezxml/stuff.jl:21
jl_is_layout_opaque at /cache/build/builder-amdci5-1/julialang/julia-master/src/julia.h:1330 [inlined]
jl_datatype_layout at /cache/build/builder-amdci5-1/julialang/julia-master/src/julia.h:1338 [inlined]
jl_f_tuple at /cache/build/builder-amdci5-1/julialang/julia-master/src/builtins.c:936 [inlined]
jl_f_tuple at /cache/build/builder-amdci5-1/julialang/julia-master/src/builtins.c:926
jl_method_error at /cache/build/builder-amdci5-1/julialang/julia-master/src/gf.c:2270
jl_lookup_generic_ at /cache/build/builder-amdci5-1/julialang/julia-master/src/gf.c:3106 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-1/julialang/julia-master/src/gf.c:3121
#17 at /home/nathan/.julia/packages/EzXML/DL8na/src/document.jl:262
unknown function (ip: 0x7f7c6fc95b5f)
xmlParserInputBufferGrow at /workspace/srcdir/libxml2-2.13.3/xmlIO.c:2362
xmlTextReaderPushData at /workspace/srcdir/libxml2-2.13.3/xmlreader.c:790
xmlTextReaderRead at /workspace/srcdir/libxml2-2.13.3/xmlreader.c:1219
macro expansion at /home/nathan/.julia/packages/EzXML/DL8na/src/error.jl:50 [inlined]
read_node at /home/nathan/.julia/packages/EzXML/DL8na/src/streamreader.jl:199 [inlined]
iterate at /home/nathan/.julia/packages/EzXML/DL8na/src/streamreader.jl:190 [inlined]
iterate at /home/nathan/.julia/packages/EzXML/DL8na/src/streamreader.jl:190
unknown function (ip: 0x7f7c6fca6b03)
top-level scope at /home/nathan/Documents/breakezxml/stuff.jl:21
jl_toplevel_eval_flex at /cache/build/builder-amdci5-1/julialang/julia-master/src/toplevel.c:934
jl_toplevel_eval_flex at /cache/build/builder-amdci5-1/julialang/julia-master/src/toplevel.c:886
ijl_toplevel_eval_in at /cache/build/builder-amdci5-1/julialang/julia-master/src/toplevel.c:994
eval at ./boot.jl:430 [inlined]
include_string at ./loading.jl:2628
_include at ./loading.jl:2688
include at ./Base.jl:557
jfptr_include_46600.1 at /home/nathan/.julia/juliaup/julia-1.11.0+0.x64.linux.gnu/lib/julia/sys.so (unknown line)
exec_options at ./client.jl:323
_start at ./client.jl:531
jfptr__start_72051.1 at /home/nathan/.julia/juliaup/julia-1.11.0+0.x64.linux.gnu/lib/julia/sys.so (unknown line)
jl_apply at /cache/build/builder-amdci5-1/julialang/julia-master/src/julia.h:2157 [inlined]
true_main at /cache/build/builder-amdci5-1/julialang/julia-master/src/jlapi.c:900
jl_repl_entrypoint at /cache/build/builder-amdci5-1/julialang/julia-master/src/jlapi.c:1059
main at /cache/build/builder-amdci5-1/julialang/julia-master/cli/loader_exe.c:58
unknown function (ip: 0x7f7c8706cd8f)
__libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x4010b8)
Allocations: 1384212 (Pool: 1384164; Big: 48); GC: 5
Segmentation fault (core dumped)
```

### PR DESCRIPTION
**Pull request by yuyichao**
* Do not manually call `pointer_from_objref`, especially when the input type may not be mutable.
* Make sure the pointer passed to libxml lasts for the duration of its use in libxml. (simply use the reader object for StreamReader case)

Fix #200
Replace #205

### CODE REVIEW

File: src/document.jl [hunk 1]
```diff
@@ -228,17 +227,16 @@ Read `input` and create an HTML document.
...
     uri = C_NULL
     encoding = C_NULL
     opts, args = parse_options(; options...)
     doc_ptr = @check ccall(
         (:htmlReadIO, libxml2),
         Ptr{_Node},
-        (Ptr{Cvoid}, Ptr{Cvoid}, Ptr{Cvoid}, Cstring, Cstring, Cint),
-        readcb, closecb, context, uri, encoding, opts) != C_NULL
+        (Ptr{Cvoid}, Ptr{Cvoid}, Ref{IO}, Cstring, Cstring, Cint),
+        readcb, closecb, input, uri, encoding, opts) != C_NULL
```
Comment (nhz2) [inline src/document.jl:239]: I'm trying to understand why this is safe. Why doesn't input need to be in a mutable struct?

Comment (yuyichao) [reply src/document.jl:239]: The value you get from the combination of cconvert and unsafe_convert is always garanteed to be safe to use for the duration the cconvert result is kept alive, which `ccall` does garantee. It won't be valid anymore outside the `ccall`, which is why this cannot be used for `StreamReader` that requires the pointer to be valid throughout the duration the `StreamReader` object is valid.

As for the implementation, one cannot ask for the pointer from an immutable object. However, if the immutable object is a field of a mutable one, then since both the address and the content of the mutable object must be stable, one can derive an address from this mutable object that remains valid as long as the mutable object is alive. The `cconvert` in this case will create a `RefValue{IO}` object and the field of that object is a pointer to the `IO` object. The `unsafe_convert` implementation loads this pointer (as a pointer and not as a julia object) from the mutable object.

**Review by nhz2 — APPROVED** [review]
Confirming that this fixes #200

**Comment by nhz2** [comment]
I guess the `StreamReader` also needs to be `GC.@preserve`ed anytime the `ptr` field is used in a `ccall`, for example:
https://github.com/JuliaIO/EzXML.jl/blob/be49969c9997b1e81c68c1aaf28dfdc3100d596c/src/streamreader.jl#L315-L322

should be:
```julia
 function hasnodevalue(reader::StreamReader) 
    r = GC.@preserve reader begin
        call( 
            (:xmlTextReaderHasValue, libxml2), 
            Cint, 
            (Ptr{Cvoid},), 
            getfield(reader, :ptr))
     end 
     return r == 1 
 end

**Comment by yuyichao** [comment]
No. The conversion should not be done manually for ccall. The correct way is to define unsafe_convert. Fixed in the latest commit.

**Comment by nhz2** [comment]
Okay, thank you, this is great. I'll merge this and make a new release.
